model_class: SASRec

model_params:
  maxlen: ${max_length}
  hidden_units: 128
  num_blocks: 3
  num_heads: 2
  dropout_rate: 0.3
patience: 10

hyper:
  hidden_units: [32, 64, 128, 256]
  num_blocks: [1, 2, 3]
  num_heads: [1, 2, 4]
  dropout_rate: [0.1, 0.3, 0.5]
